# Set theme
theme: alembic-jekyll-theme

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji

# Site settings
url: 'https://gishi.tech'
baseurl: ''
title: 'ARIA'
description: 'Administration, Registration, and Information Assistant'
permalink: pretty
logo: "https://imgur.com/download/F8Dfprf"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
  Home: /
  Project Video: /projectvideo
  Project Poster: /projectposter
  Documentation: /documentation
  Source Code: https://github.com/invainn/ARIA
  Team Members: /team/
  Advisors & Instructors: /adv/

# Footer nav
navigation_footer:
  Return to Home: "#top"

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "My thoughts and ideas"
    feature_text: |
      Welcome to my blog
    feature_image: "https://picsum.photos/2560/600?image=866"
